# Generated by Django 3.2.13 on 2023-02-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230203_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
