# Generated by Django 3.2.13 on 2023-02-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230203_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['timeslot', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'period']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
