# Generated by Django 3.2.13 on 2023-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230204_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
