# Generated by Django 3.2.13 on 2023-02-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230205_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'period')},
        ),
    ]
